apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kata-backend
  annotations:
    github.com/project-slug: jfarfa3/kata-backend
spec:
  type: other
  lifecycle: unknown
  owner: guests
