services:
  db:
    image: postgres
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - cinema-db-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-dbs.sql
    container_name: cinema-postgres-db

volumes:
  cinema-db-data:
